name: komus24
version: 0.1.0

dependencies:
  - base
  - containers
  - text
  - binary
  - bytestring
  - network
  - transformers

executables:
  komus24:
    main: Main.hs
    source-dirs: src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    default-extensions:
      - ScopedTypeVariables
      - TypeSynonymInstances
      - FlexibleInstances
      - NamedFieldPuns
      - DuplicateRecordFields